In [29]:
import numpy
n = numpy.arange(27)
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [49]:
m = numpy.asarray([[1,2,3], [4,5,6], [7,8,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
import cv2
im_g = cv2.imread("smallgray.png",0)    # 0 for grayscale, 1 for bgr... defuault is 1
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [60]:
cv2.imwrite("newsmallgray.png", im_g)

True

In [86]:
im_g[2,4]


182

In [106]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [125]:
ims = numpy.hstack((im_g, im_g, im_g))  #hstack((n, n, n)) and vstack((n, n, n))
print(ims)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [156]:
imv = numpy.vstack((im_g, im_g, im_g))
imv

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [159]:
hlst = numpy.hsplit(ims, 3)     #hsplit(array, amount) and vsplit(array, amount)
hlst    #hlst is a list of arrays

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]